# CIS 443-01 Exam 2, Part 2 Notebook
## 35 pts. plus 5 pts. Extra Credit
## Directions
1. Add your Grading ID below.
1. Answer each question in the cells provided.
1. When finished, save your work, close the Jupyter Lab file, and Shut Down Jupyter Lab. You will upload this Jupyter Notebook file as your submission to Question 1 in Exam 2, Part 2 in Blackboard.
1. Be sure to keep an unaltered version of this file just in case anything goes wrong in Blackboard.

__Grading ID__: P8330 (double click the cell in Jupyter to edit)

### Problem 1
Write a Python code fragment in the code cell below that uses a _list comprehension_ to map the range of integers from 1 through 20 (inclusive) onto the square of each value but filtered to only operate on the odd numbers in the range (producing the square of 1, the square of 3, etc.). (__7 pts.__)

In [1]:
int_list = []
list_comp = [ item for item in range(1, 20) if item % 2 != 0]

for i in list_comp:
    triple = i * 3
    int_list.append(triple)
    
int_list


[3, 9, 15, 21, 27, 33, 39, 45, 51, 57]

### Problem 2
Write a Python code fragment in the code cell below that inputs a line of text from the user, tokenizes the text using space characters as delimiters and outputs only those words ending with the letters `'ing'`. Ignore the case of the words. (__7 pts.__)

In [4]:
s = input('Enter a line of text: ').lower() 
words = s.split() 
starts_with_str = 'ing' 
print(f'The words that ends with {starts_with_str}')
for word in words: 
  if word.endswith(starts_with_str): 
    print(word)        

Enter a line of text:  starting 


The words that ends with ing
starting


### Problem 3
Write a Python code fragment in the code cell below that defines a function named `calc_qual_pts` that accepts a letter grade (a string) as a parameter and returns the GPA quality points, as specified below, <u>using a dictionary that maps each letter grade to its associated quality points</u>. If the grade is not one of the standard letter grades (A, B, C, D, F), return -1 to indicate this. Test the function with grades of "A", "C", and "X". (__8 pts.__)

| Grade | Quality Points |
| ----- | -------------- |
| A     | 4.0            |
| B     | 3.0            |
| C     | 2.0            |
| D     | 1.0            |
| F     | 0.0            |
| Otherwise | -1         |

In [2]:
def calc_qual_pts(grade):
    QA_points = {'A': 4.0, 'B': 3.0,'C': 2.0,'D': 1.0, 'F': 0.0, 'X': -1}
    return QA_points[grade]

print(calc_qual_pts('A'))
print(calc_qual_pts('C'))
print(calc_qual_pts('X'))

4.0
2.0
-1


### Problem 4
Write a Python code fragment in the code cell below that implements a function named `merge_to_dict` that will accept two parallel lists as parameters, the `key_list` and the `value_list`, and will return a dictionary of the associated key-value pairs. Write your own loop to accomplish this (don't just call `zip`!). You may assume that the lists are the same length. Test with a list of 3 names as keys and a list of 3 test scores as the values. (__7 pts.__)

In [6]:
def merge_to_dict(key_list, value_list):
     
    key_list = []
    value = []
    val_dict = {}
        
    for k, v in  val_dict(zip(key_list, value_list)):
              
        return val_dict


key = ['Scott', 'Jason', 'Matt']
value = [90, 80 , 70]

print(merge_to_dict(key, value))   

NameError: name 'key_list' is not defined

### Problem 5
Use _arange_ to create a 2-by-2 _ndarray_ containing the numbers 1–4. Use _broadcasting_ to perform each of the following operations on the original array creating a new _ndarray_ and printing its contents: (__2 pts. each__)
1. Cube every element of the array.
1. Add 20 to every element of the array.
1. Multiply every element of the array by 5.

In [14]:
import numpy as np

num_array = np.arange(1, 5)
cube = num_array ** 3

twenty = num_array.copy()
twenty_array = twenty + 20

multi = num_array.copy()
five_array = multi * 5

print(cube)
print(twenty_array)
print(five_array)

[ 1  8 27 64]
[21 22 23 24]
[ 5 10 15 20]


### Problem 6 - Extra Credit
Use a regular expressions and the `sub` function to remove any extra spaces between words of an input string and display the results. For example,<br />`'Hello   There    World'`<br />should become<br />`'Hello There World'`<br /> (__5 pts. Extra Credit__)

In [17]:
import re 

re.sub(r'\t', ', '[a-z][A-Z])

input 

NameError: name 'a' is not defined

Be sure to save and exit your Jupyter Notebook and Shutdown Jupyter Lab (from the __File__ menu) if using Ananconda before you submit your notebook on Blackboard for grading. If using Colab, be sure to Download (from the __File__ menu) back to your local file system before submitting to Blackboard.
Make sure you don't submit the empty starting notebook by accident.